# -*- coding: utf-8 -*-
"""Toderinde_MadLibs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BsTggGyl9_HejUEdQkoGZITe0009jIm8
"""

#imports
import random

#this function will ask the user for a word based on the word provided as parameter
def ask_for_word(word):
    newWord = input("Enter a(n) " + word + ":")
    return newWord


#open the file with the madlib sentences
file = open("MadLib Sentences.txt")

#store the lines in a list
lines = file.readlines()

file.close()

#choose a random line to use
line = random.choice(lines)

#this will be the current word to ask for
word = ""
addToWord = False

#this will be the new, modified sentence
newLine = ""

#iterate through the line to find
for c in line:

    #if addtoword is true we save the character in the word variable
    #to latter ask the user for the word
    if addToWord:
        word += c
    #if not, we add the unchanged character to the new line
    else:
        newLine += c

    #when we see the < symbol we turn addtoword to true to start recording the word
    if c == "<":
        addToWord = True
    #when we see the > symbol we stop recording the word and we ask the user for an input
    #we also add the input by the user to the newline
    elif c == ">":
        addToWord = False
        newWord = ask_for_word(word[:-1])
        newLine += newWord + ">"
        word = ""

print(newLine)